name: Rust Code Coverage

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install grcov
        run: |
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
          sudo mv grcov /usr/local/bin/

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install llvm-tools
        run: rustup component add llvm-tools-preview

      - name: Build and Test with Coverage
        run: |
          export RUSTFLAGS="-Cinstrument-coverage"
          cargo build --verbose
          LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          file: lcov.info
