name: Release 📦

on:
  push:
    branches:
      - "**"
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest] #macOS-latest, windows-latest

      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Setup Rust
          uses: dtolnay/rust-toolchain@v1
          with:
            toolchain: stable

        - name: Setup MUSL
          if: matrix.os == 'ubuntu-latest'
          run: |
            rustup target add x86_64-unknown-linux-musl
            sudo apt-get -qq install musl-tools

        - name: Build for ${{ matrix.os }} (arm64/amd64)
          if: matrix.os == 'ubuntu-latest'
          run: |
            make release-linux

        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            body: '[Changelog](https://github.com/containerscrew/aws-sso-auth/blob/main/CHANGELOG.md)'
            files: "*.zip\n*.rpm"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
