name: Release 📦

on:
  push:
#    branches:
#      - "*"
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build for macOS
        if: matrix.os == 'macOS-latest'
        run: make release_mac

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: '[Changelog](https://github.com/containerscrew/aws-sso-rs/blob/main/CHANGELOG.md)'
          files: "*.zip\n*.rpm"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
