name: Release 📦

on:
  push:
    branches:
      - "**"
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build for ${{ matrix.os }} - ${{ matrix.arch }}
        if: matrix.os == 'ubuntu-latest'
        run: |
          make release


      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aws-sso-auth-${{ matrix.os }}-${{ matrix.arch }}
          path: target/release/
